### ISSUE TITLE
V1 tracking

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/uniffi-dart#12]
- [ ] Futures and Async Dart
- [ ] Callbacks
- [ ] Command Line Interface
- [ ] Collections Types (Maps, Sequences)
- [ ] Other Types (Bytes, Timestamp, Duration, Custom)
- [ ] External crates
- [ ] Fixtures/Tests
- [ ] Memory Optimizations.
- [ ] Better Internal documentation
- [ ] Old Code Removal
- [ ] Refine Old Test to have all types
